name: 'S&V Photography'
favicon: null
layout_spectrum: 0.760223250137642
typography_spectrum: 0.5960008504334837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9636971061117947
  lightness: 0.3879552613943815
  saturation: 0.08858890715055168
  rhythmicContrast: 0.15492680063471198
purpose: []
